[package]
name = "tbh-database"
description = "High-level access to database entities"
version = "1.0.0"
edition = "2024"
authors = ["Lennox Schneider <admin@lennoxlotl.dev>"]

[dependencies]
rusqlite = { version = "0.37.0", features = ["bundled-windows"] }
eyre = "0.6.12"
r2d2 = "0.8.10"
r2d2_sqlite = "0.31.0"
